version: '3'
services:
 fastapi:
  build:
   context: .
   dockerfile: app/Dockerfile
  ports:
   - "8000:8000"
  depends_on:
    - db
  env_file:
    - .env
    
 db:
  image: postgres:13-alpine
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  environment:
   - POSTGRES_USER=FlynnTest
   - POSTGRES_PASSWORD=FlynnTest123
   - POSTGRES_DB=db
  ports:
   - 5432:5432

volumes:
 postgres_data: